let wordList = [
    // ---------------- EASY (20) ----------------
    { word: "dog", hint: "A common household pet known for loyalty." },
    { word: "sun", hint: "The star that provides light and heat to Earth." },
    { word: "book", hint: "A collection of written or printed pages." },
    { word: "teddyllanda", hint: "Best programming teacher in Eastwoods Professional Collage of Science" },
    { word: "chair", hint: "A piece of furniture used for sitting." },
    { word: "water", hint: "A clear liquid essential for life." },
    { word: "flower", hint: "A colorful plant part that blooms." },
    { word: "train", hint: "A long vehicle that travels on tracks." },
    { word: "fish", hint: "An animal that lives and swims in water." },
    { word: "milk", hint: "A white liquid produced by mammals." },
    { word: "tree", hint: "A tall plant with a trunk and branches." },
    { word: "cat", hint: "A small furry pet known for meowing." },
    { word: "pizza", hint: "A popular dish made with dough, sauce, and cheese." },
    { word: "phone", hint: "A device used for communication." },
    { word: "beach", hint: "A sandy area beside the sea." },
    { word: "ball", hint: "A round object used in many games." },
    { word: "bird", hint: "An animal that has wings and can often fly." },
    { word: "snow", hint: "Frozen white crystals that fall in cold weather." },
    { word: "car", hint: "A vehicle used for transportation." },
    { word: "shoe", hint: "Footwear worn for protection and comfort." },

    // ---------------- MEDIUM (20) ----------------
    { word: "bridge", hint: "A structure used to cross over water or roads." },
    { word: "airport", hint: "A place where airplanes take off and land." },
    { word: "jungle", hint: "A thick forest filled with wildlife." },
    { word: "camera", hint: "A device used to capture photos and videos." },
    { word: "planet", hint: "A large object that orbits a star." },
    { word: "puzzle", hint: "A game that requires solving pieces or clues." },
    { word: "forest", hint: "A large area covered with trees." },
    { word: "festival", hint: "A celebration often with music and food." },
    { word: "candle", hint: "A stick of wax that produces light when lit." },
    { word: "harbor", hint: "A protected place where ships dock." },
    { word: "teacher", hint: "Someone who educates students." },
    { word: "blanket", hint: "A warm covering used while sleeping." },
    { word: "mountain", hint: "A large natural elevation of land." },
    { word: "umbrella", hint: "A tool used to protect yourself from rain." },
    { word: "painter", hint: "An artist who creates artwork using colors." },
    { word: "cactus", hint: "A spiky plant that grows in deserts." },
    { word: "library", hint: "A place where books are stored and borrowed." },
    { word: "engineer", hint: "A person who designs or builds systems or structures." },
    { word: "compass", hint: "A navigational tool used to find directions." },
    { word: "theater", hint: "A place where movies or plays are shown." },

    // ---------------- HARD (20) ----------------
    { word: "algorithm", hint: "A step-by-step method used to solve a problem." },
    { word: "paradox", hint: "A statement that contradicts itself yet may be true." },
    { word: "quarantine", hint: "Isolation used to prevent the spread of disease." },
    { word: "hemisphere", hint: "Half of a sphere, often referring to halves of Earth." },
    { word: "photosynthesis", hint: "The process plants use to make food using sunlight." },
    { word: "biodiversity", hint: "The variety of life within an ecosystem." },
    { word: "cathedral", hint: "A large and important Christian church building." },
    { word: "ecosystem", hint: "A community of organisms interacting with the environment." },
    { word: "amphibian", hint: "An animal that can live both in water and on land." },
    { word: "conscience", hint: "A personal sense of right and wrong." },
    { word: "renaissance", hint: "A period of cultural and artistic revival in Europe." },
    { word: "astronaut", hint: "A person trained to travel into space." },
    { word: "philosophy", hint: "The study of ideas about existence and knowledge." },
    { word: "metaphor", hint: "A figure of speech that directly compares two things." },
    { word: "synthesis", hint: "The combination of elements to form a new whole." },
    { word: "geology", hint: "The study of Earth's structure, materials, and processes." },
    { word: "thermodynamics", hint: "The study of energy, heat, and work." },
    { word: "archaeology", hint: "The study of human history through artifacts." },
    { word: "radiation", hint: "Energy emitted as waves or particles." },
    { word: "hypothesis", hint: "A proposed explanation based on limited evidence." }
];
